Crncc 1461 vs cms welsh 1 6 emails
PA-NIHR-CRN/dte-common pull request #7
Opened 2023-09-07 09:00 UTC by paddyduff31

2023-09-07 10:39 UTC, con-nihr requested changes
Love it. Well done.

Do you need to incorporate this in to the api and event handlers now?

2023-09-07 10:39 UTC, con-nihr commented on Dte.Common/Services/ContentfulService.cs
> +        private static string ToTitleCase(string input, CultureInfo cultureInfo)
Nice

2023-09-07 10:39 UTC, con-nihr commented on Dte.Common/Http/ContentfulClient.cs
Probably best to name this file and the class `ContentfulServiceCollectionExtensions.cs`.

FYI, some projects use a trick by adding these extensions to the `Microsoft.Extensions.DependencyInjection` namespace.

That way you get Intellisense directly in your Startup.cs when you add a reference to the library.

e.g.
...
AddContentfulServices()
AddRazorPages()
AddHttpClient()
...etc

see https://github.com/AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection/blob/master/src/AutoMapper.Extensions.Microsoft.DependencyInjection/ServiceCollectionExtensions.cs

Not suggesting you need to do this, but something to be aware of.

2023-09-07 13:04 UTC, paddyduff31 commented
Yes, it now just has to be implemented but I need access to the package services so I need to get this deployed first before updating the other 2

2023-09-07 13:24 UTC, paddyduff31 commented on Dte.Common/Http/ContentfulClient.cs
Apologies, I just did the class name itself!!!

Done

2023-09-07 13:59 UTC, paddyduff31 commented
Added BaseUrl to the request so common knows the env we are in

2023-09-08 08:28 UTC, con-nihr approved these changes

2023-09-08 10:36 UTC, merged